export const maxWidth = '800px';
export const textColor = '#222222';
export const iconColor = '#444444';
export const primaryColor = '#55BABF';
export const primaryColorLight = '#E6FEFF';
export const primaryColorDark = '#458083';
export const secondaryColor = '#D34A3A';
export const textFont = 'Roboto, sans-serif';
export const codeFont = 'Roboto Mono, monospace';
